services:
  sistemmanagementtpqbaitusshuffahreact:
    image: sistemmanagementtpqbaitusshuffahreact
    build:
      context: .next
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
